all: compilelink run

compilelink:
	g++ main.cpp src/timers.cpp ../Problem7/src/tridiagAlgo.cpp ../Problem9/src/specialTridiagAlgo.cpp ../Problem2/src/utils.cpp -I include -o timer.out 

run:
	./timer.out
